<?xml version="1.0"?>
<package format="2">
  <name>small_house_world</name>
  <version>1.0.0</version>
  <description>
    Small house world with multiple rooms and furniture for Gazebo simulations (migrated from Gazebo Classic to Gazebo).
  </description>
  <license>Apache 2.0</license>
  <author email="ros-contributions@amazon.com">AWS RoboMaker</author>
  <maintainer email="ros-contributions@amazon.com">AWS RoboMaker</maintainer>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>gz-sim</exec_depend>

  <export>
   <build_type>ament_cmake</build_type>
   <gazebo gazebo_model_path="${prefix}/models" gazebo_resource_path="${prefix}"/>
  </export>
</package>
